version: '3.3'
services:
  load-balancer:
    hostname: load-balancer
    image: nginx:latest
    volumes:
      - ../../configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
  db:
    hostname: postgresql
    container_name: postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 1s
      retries: 5
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: zenehu
      POSTGRES_PASSWORD: zenehu
      POSTGRES_DB: forum-task
    network_mode: host
    volumes:
      - ../../db/db.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  prometheus:
    hostname: prometheus
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    network_mode: host
    volumes:
      - prometheus_data:/prometheus
      - ../../configs/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=zenehu
      - GF_SECURITY_ADMIN_PASSWORD=secretkey
      - GF_USERS_ALLOW_SIGN_UP=true
    network_mode: host

  node-exporter:
    hostname: node-exporter
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    network_mode: host

volumes:
  prometheus_data: { }
  grafana_data: { }
